# Site settings
title: Jekyll 3.x.x. Test Site
email: jekyll@tester.com
description: >- # this means to ignore newlines until "baseurl:"
  Plain Jekyll installation to test plugin versions
baseurl: ""
url: "https://erikw.github.io/jekyll-3.x.x-test/"
github_username:  erikw

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - bin/
  - Rakefile
  - Gemfile*
  - README.md

plugins:
  - jekyll-feed
  - jekyll-google_search_console_verification_file
  - jekyll-glossary_tooltip

google_search_console:
  verification_file_code: 1234
